### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by eranrund** [FundersClub/bai-lockbox#1]
- [x] https://github.com/FundersClub/bai-lockbox/blob/master/setup.py#L12 - are all of these used?
- [x] https://github.com/FundersClub/bai-lockbox/blob/master/setup.py#L20 - incorrect
- [x] https://github.com/FundersClub/bai-lockbox/blob/master/lockbox/exceptions.py#L32 - what is this?
- [x] https://github.com/FundersClub/bai-lockbox/blob/master/lockbox/parser.py#L70 - Where is `.get()` defined?
- [x] https://github.com/FundersClub/bai-lockbox/blob/master/lockbox/parser.py#L81 - Why not something like `return map(Check, self.details)` (or good ol' list comprehension)
- [x] https://github.com/FundersClub/bai-lockbox/blob/master/lockbox/parser.py#L269 - Look up `enumerate()`
- [x] https://github.com/FundersClub/bai-lockbox/blob/master/lockbox/parser.py#L266 and https://github.com/FundersClub/bai-lockbox/blob/master/lockbox/parser.py#L311 - I would make these `@classmethod`s in `LockboxFile` and call them something like `from_lines` and `from_file`
- [x] https://github.com/FundersClub/bai-lockbox/blob/master/lockbox/parser.py#L312 - I would make the `read_lockbox_lines` perform the `strip()` as it is always desired
- [x] https://github.com/FundersClub/bai-lockbox/blob/master/lockbox/parser.py#L271 - Instead of all those `str()` and repeating `line[0]` why not: 1) convert `int(line[0])` and store it in a local variable and then compare. 2) Create a dictionary that maps the record number to the class. (see *1 below)
- [x] https://github.com/FundersClub/bai-lockbox/blob/master/lockbox/records.py#L70 - Please use `iteritems`, no need to create an in-memory list
- [x] https://github.com/FundersClub/bai-lockbox/blob/master/lockbox/records.py#L85 - `iteritems()`
- [x] https://github.com/FundersClub/bai-lockbox/blob/master/lockbox/records.py#L94 - `start_col, end_col = field_def['location']`
- [x] I think we should make field types a constant and then use that. Reduces chances for unnoticed typos. (see *2 below)

---

*1

```
class FieldType(object):
    Numeric = 'numeric'
    ...
```

---

*2  

```
record_types = {
    LockboxBatchTotalRecord.RECORD_TYPE_NUM: LockboxBatchTotalRecord,
    ....
}

record_cls = record_types.get(int(line[0]))
if not record_cls: ...
rec = record_cls(line)
```

**Comment by eranrund** [comment]
Not familiar with the format itself and parsing infrastructure looks elegant - issues are mostly nits.

**Comment by j-friedman** [comment]
Heh. It also looks like I copied your `setup.py` and forgot to update the description. Whooops
